### ISSUE TITLE
Dynamic App

### ISSUE THREAD

**Issue by pnijhara** [cbmi-uthsc/webSCAS#6]
Hi, this idea seems great to me, I would like to work on it.

**Comment by duddu-coder** [comment]
# Bhaiyye
Code kaha dikh gaya tujhe?

**Comment by duddu-coder** [comment]
The current codebase is exceptionally good.
I would love to contribute to such a codebase.
Can I be assigned this issue please?

Have Milk,
Thanks

**Comment by pnijhara** [comment]
Already sent PR

**Comment by pnijhara** [comment]
@akram-mohammed please respond.
